//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AerolíneaEntities : DbContext
    {
        public AerolíneaEntities()
            : base("name=AerolíneaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerolinea> Aerolinea { get; set; }
        public virtual DbSet<Aeropuerto> Aeropuerto { get; set; }
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Boleto> Boleto { get; set; }
        public virtual DbSet<Cambio_Moneda> Cambio_Moneda { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<MetodoDePago> MetodoDePago { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Piloto> Piloto { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
    }
}
