//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleto()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int Id_Boleto { get; set; }
        public string Persona_Pasajero { get; set; }
        public string Origen_Vuelo { get; set; }
        public string Destino_Vuelo { get; set; }
        public Nullable<System.DateTime> Fecha_Vuelo { get; set; }
        public Nullable<System.DateTime> Hora_Vuelo { get; set; }
        public string TipoPasajero_Vuelo { get; set; }
        public string Clase_Vuelo { get; set; }
        public int Destino { get; set; }
        public int Id_Vuelo { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Asiento { get; set; }
        public int ID_Responsable { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Responsable Responsable { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vuelo Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
