//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public int Id_Pago { get; set; }
        public Nullable<int> Codigo_ID_Bancaria { get; set; }
        public Nullable<int> Numero_Cuenta { get; set; }
        public Nullable<int> Numero_Telefono { get; set; }
        public string Tipo_Pago { get; set; }
        public string Fecha_Pago { get; set; }
        public decimal Cantidad_Pago { get; set; }
        public int ID_METODO { get; set; }
        public int Id_Tarjeta { get; set; }
        public int ID_Cambio { get; set; }
    
        public virtual Cambio_Moneda Cambio_Moneda { get; set; }
        public virtual MetodoDePago MetodoDePago { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
    }
}
