//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int Id_Tarjeta { get; set; }
        public string Nombre_Tarjeta { get; set; }
        public Nullable<int> Numero_Tarjeta { get; set; }
        public string Tipo_Tarjeta { get; set; }
        public Nullable<System.DateTime> Fecha_Tarjeta { get; set; }
        public Nullable<System.DateTime> Vencimiento_Tarjeta { get; set; }
        public int Id_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
