//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.Boleto = new HashSet<Boleto>();
            this.Piloto = new HashSet<Piloto>();
        }
    
        public int Id_Vuelo { get; set; }
        public Nullable<int> Num_Vuelo { get; set; }
        public string Origen_Vuelo { get; set; }
        public string Destino_Vuelo { get; set; }
        public Nullable<System.DateTime> Fecha_Vuelo { get; set; }
        public Nullable<System.DateTime> Hora_Vuelo { get; set; }
        public string TipoPasajero_Vuelo { get; set; }
        public string Clase_Vuelo { get; set; }
        public int Id_Avion { get; set; }
        public int ID_Ruta { get; set; }
        public int ID_Precio { get; set; }
    
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Precio Precio { get; set; }
        public virtual Ruta Ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Piloto> Piloto { get; set; }
    }
}
